language: objective-c
xcode_project: ArtikCloudTests/ArtikCloudClient.xcodeproj # path to your xcodeproj folder
xcode_scheme: ArtikCloudClientTests
script:
  - xcodebuild [DEFAULT_OPTIONS] CODE_SIGNING_REQUIRED=NO